#!/usr/bin/env bash

## IVO.Group package, v1.0
##
## Website: https://ivo.group
## Author: ivan.berezhnov@icloud.com
##
## Initialize stack and site (full reset)
##
## Usage: fin init
## Usage: fin init new

# Abort if anything fails
set -e

CURRENT_DIR="$(dirname "$0")"
source "${CURRENT_DIR}/includes/helpers.sh"

#-------------------------- Settings --------------------------------

# PROJECT_ROOT is passed from fin.
# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST.
SITEDIR_PATH="${DOCROOT_PATH}/sites/default"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------
# Set file/folder permissions
file_permissions ()
{
  chmod -R a+w "${SITEDIR_PATH}"
  mkdir -p "$DOCROOT_PATH/sites/$SITE_DIRECTORY/files"
  chmod 777 "$DOCROOT_PATH/sites/$SITE_DIRECTORY/files"
}

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
  local source="$1"
  local dest="$2"

  if [[ ! -f $dest ]]; then
    echo "Copying ${dest}..."
  	cp $source $dest
  else
  	echo "${dest} already in place."
  fi
}

# Initialize local settings files
init_settings ()
{
  # Copy from settings templates
  copy_settings_file "${PROJECT_ROOT}/.docksal/settings/development.services.yml" "${SITEDIR_PATH}/development.services.yml"
  copy_settings_file "${PROJECT_ROOT}/.docksal/settings/setting.stage_file_proxy.php" "${SITEDIR_PATH}/setting.stage_file_proxy.php"
  copy_settings_file "${PROJECT_ROOT}/.docksal/settings/settings.local.php" "${SITEDIR_PATH}/settings.local.php"
  echo -e "${green} Done. ${NC}"
}

# Installing composer
composer_install ()
{
	cd $PROJECT_ROOT
	fin composer install --no-ansi --no-dev --no-interaction --optimize-autoloader --no-progress --prefer-dist --ignore-platform-reqs
}

# Install site
site_install ()
{
    echo -e "${green} Installing site...${NC}"
	cd $DOCROOT_PATH
	# We disable email sending here so site-install does not return an error
	fin drush site-install -y --site-name='DRUPAL 8 Starter Kit' --account-name='admin' --account-pass='admin'
}

post_install ()
{
  cd ${DOCROOT_PATH}

  echo-yellow "Running database updates ..."
  fin drush updb -y

# TODO: Uncommented it if needs.
#  echo-yellow "Importing configuration sync files ..."
#  fin drush cim -y

  echo-green "Change admin password ..."
  fin drush upwd "admin" --password="admin"

  echo-yellow "Enabling and configuring stage_file_proxy ..."
#  fin drush en -y stage_file_proxy

  echo-yellow "Enabling developer modules ..."

  echo-yellow "Clearing cache ..."
  fin drush cr
}

# Post install commands
#post_install ()
#{
#    if [ "$1" == "new" ]; then
#        echo -e "${yellow}http://${VIRTUAL_HOST}/user${NC}"
#        echo -e "User:${green} admin ${NC}"
#        echo -e "Pass:${green} admin ${NC}"
#    else
#        drush uli
#    fi
#}

# Install site
site_theme ()
{
  echo-yellow "Build theme styles"
  if [ -f "${MAIN_THEME_PATH}/package-lock.json" ]; then
     rm "${MAIN_THEME_PATH}/package-lock.json"
  fi
  fin tb
}
#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------
# Stack initialization
if [[ "$PROJECT_ROOT" == "" ]]; then
  echo-red "\$PROJECT_ROOT is not set"
  exit 1
fi

if [[ $DOCKER_RUNNING == "true" ]]; then
  echo -e "${green_bg}Step 1${NC}${green} Recreating services...${NC}"
  fin reset -f
else
  echo -e "${green_bg}Step 1${NC}${green} Creating services...${NC}"
  fin up
fi
echo "Waiting 10s for MySQL to initialize...";
sleep 10

echo -e "${green_bg}[Step 2]${NC}${green} Installing composer...${NC}"
composer_install

echo -e "${green_bg}[Step 3]${NC}${green} Copying settings ...${NC}"
init_settings

echo -e "${green_bg}[Step 4]${NC}${green} Installing site ...${NC}"
site_install

echo -e "${green_bg}[Step 5]${NC}${green} Executing post-install commands ...${NC}"
post_install

echo -e "${green_bg}[Step 6]${NC}${green} Setting file/folder permissions...${NC}"
file_permissions

echo -e "${green_bg}[Step 7]${NC}${green} Build theme styles ...${NC}"
#site_theme

echo -e "${green_bg}DONE!${NC}"
echo -e "Open ${yellow}http://${VIRTUAL_HOST}/user/login${NC} in your browser to verify the setup."
echo -e "Account: ${yellow}admin // admin ${NC}"
#-------------------------- END: Execution --------------------------------
